import jsPDF from 'jspdf';
import 'jspdf-autotable';

interface RowData {
  field1: string;
  field2: string;
  field3: string;
  field4: string;
}

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

declare module 'jspdf-autotable';
// utils/generateInvoicePDF.ts

interface RowData {
  field1: string;
  field2: string;
  field3: string;
  field4: string;
}
interface InvoiceRow {
  field: string;
  value: string | number;
}

interface Column {
  header: string;
  dataKey: keyof RowData;
}

const generateInvoicePDF = (rowData: InvoiceRow[]): void => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(40);
  doc.setFont('helvetica', 'normal');
  doc.text('Invoice', 14, 22);

  // Subtitle
  doc.setFontSize(16);
  doc.text('Transaction Details', 14, 32);

  // Spacer
  doc.setFontSize(12);
  doc.text(' ', 14, 38);

  // Define the table columns and rows
  const columns = [
    { header: 'Field', dataKey: 'field' },
    { header: 'Value', dataKey: 'value' },
  ];

  // Add the table with styles
  doc.autoTable({
    startY: 40,
    head: [columns.map(col => col.header)],
    body: rowData.map(row => [row.field, row.value]),
    theme: 'grid',
    headStyles: {
      fillColor: [22, 160, 133],
      textColor: [255, 255, 255],
      fontSize: 12,
    },
    bodyStyles: {
      fillColor: [240, 240, 240],
      textColor: [0, 0, 0],
      fontSize: 10,
    },
    alternateRowStyles: {
      fillColor: [255, 255, 255],
    },
    styles: {
      cellPadding: 3,
    },
  });

  // Add footer
  doc.setFontSize(10);
  doc.text('Generated by MyApp', 14, doc.internal.pageSize.height - 10);

  // Save the PDF
  doc.save('invoice.pdf');
};

export default generateInvoicePDF;
