import { ManagementUser } from './user-management';

export const MORE_DUMMY_USERS: ManagementUser[] = [
  {
    id: '12180001',
    username: 'alphaCoder',
    name: 'Alice Johnson',
    email: 'alice.johnson@gmail.com',
    registrationDate: '12 JAN 2025',
    assetHoldings: 120000,
    affiliates: 12,
    status: 'Active',
    kycStatus: 'Approved',
    lastLogin: '10 JAN 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'France',
    phone: '91234567890',
    ip: '128.1.123.100',
    referral: 'referral.alice@example.com',
    AffiliateStatus: 'Yes',
    is_demo: false,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 12,
  },
  {
    id: '12180002',
    username: 'betaBuilder',
    name: 'Bob Smith',
    email: 'bob.smith@gmail.com',
    registrationDate: '05 FEB 2025',
    assetHoldings: 125500,
    affiliates: 8,
    status: 'Suspended',
    kycStatus: 'Need Information',
    lastLogin: '15 FEB 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'Germany',
    phone: '91234567891',
    ip: '128.1.123.101',
    referral: 'referral.bob@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: false,
    meta_assets_count: 12,
    noOfAffiliates: 8,
  },
  {
    id: '12180003',
    username: 'charlieRunner',
    name: 'Charlie Lee',
    email: 'charlie.lee@gmail.com',
    registrationDate: '20 MAR 2025',
    assetHoldings: 101000,
    affiliates: 15,
    status: 'Inactive',
    kycStatus: 'Approved',
    lastLogin: '20 MAR 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'Spain',
    phone: '91234567892',
    ip: '128.1.123.102',
    referral: 'referral.charlie@example.com',
    AffiliateStatus: 'Yes',
    is_demo: false,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 15,
  },
  {
    id: '12180004',
    username: 'deltaWave',
    name: 'Dana White',
    email: 'dana.white@gmail.com',
    registrationDate: '15 APR 2025',
    assetHoldings: 98000,
    affiliates: 20,
    status: 'Blocked',
    kycStatus: 'Need Information',
    lastLogin: '25 APR 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'France',
    phone: '91234567893',
    ip: '128.1.123.103',
    referral: 'referral.dana@example.com',
    AffiliateStatus: 'No',
    is_demo: false,
    is_admin: false,
    is_rewards_enabled: false,
    meta_assets_count: 12,
    noOfAffiliates: 20,
  },
  {
    id: '12180005',
    username: 'echoSky',
    name: 'Evan Thomas',
    email: 'evan.thomas@gmail.com',
    registrationDate: '08 MAY 2025',
    assetHoldings: 110500,
    affiliates: 5,
    status: 'Active',
    kycStatus: 'Approved',
    lastLogin: '30 MAY 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'Germany',
    phone: '91234567894',
    ip: '128.1.123.104',
    referral: 'referral.evan@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 5,
  },
  {
    id: '12180006',
    username: 'foxtrotNine',
    name: 'Fiona Brown',
    email: 'fiona.brown@gmail.com',
    registrationDate: '22 JUN 2025',
    assetHoldings: 143200,
    affiliates: 9,
    status: 'Suspended',
    kycStatus: 'Need Information',
    lastLogin: '05 JUN 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'Spain',
    phone: '91234567895',
    ip: '128.1.123.105',
    referral: 'referral.fiona@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 9,
  },
  {
    id: '12180007',
    username: 'golfGuru',
    name: 'George Martin',
    email: 'george.martin@gmail.com',
    registrationDate: '12 JUL 2025',
    assetHoldings: 157000,
    affiliates: 11,
    status: 'Inactive',
    kycStatus: 'Approved',
    lastLogin: '10 JUL 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'France',
    phone: '91234567896',
    ip: '128.1.123.106',
    referral: 'referral.george@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 11,
  },
  {
    id: '12180008',
    username: 'hotelHero',
    name: 'Hannah Clark',
    email: 'hannah.clark@gmail.com',
    registrationDate: '05 AUG 2025',
    assetHoldings: 135000,
    affiliates: 7,
    status: 'Blocked',
    kycStatus: 'Need Information',
    lastLogin: '15 AUG 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'Germany',
    phone: '91234567897',
    ip: '128.1.123.107',
    referral: 'referral.hannah@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 7,
  },
  {
    id: '12180009',
    username: 'indiaKnight',
    name: 'Ian Wright',
    email: 'ian.wright@gmail.com',
    registrationDate: '20 SEP 2025',
    assetHoldings: 101500,
    affiliates: 14,
    status: 'Active',
    kycStatus: 'Approved',
    lastLogin: '20 SEP 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'Spain',
    phone: '91234567898',
    ip: '128.1.123.108',
    referral: 'referral.ian@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 14,
  },
  {
    id: '12180010',
    username: 'julietJazz',
    name: 'Julia Adams',
    email: 'julia.adams@gmail.com',
    registrationDate: '15 OCT 2025',
    assetHoldings: 99000,
    affiliates: 6,
    status: 'Suspended',
    kycStatus: 'Need Information',
    lastLogin: '25 OCT 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'France',
    phone: '91234567899',
    ip: '128.1.123.109',
    referral: 'referral.julia@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 6,
  },
  {
    id: '12180011',
    username: 'kiloKing',
    name: 'Kevin Baker',
    email: 'kevin.baker@gmail.com',
    registrationDate: '08 NOV 2025',
    assetHoldings: 125000,
    affiliates: 13,
    status: 'Inactive',
    kycStatus: 'Approved',
    lastLogin: '30 NOV 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'Germany',
    phone: '91234567900',
    ip: '128.1.123.110',
    referral: 'referral.kevin@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 13,
  },
  {
    id: '12180012',
    username: 'limaLancer',
    name: 'Linda Scott',
    email: 'linda.scott@gmail.com',
    registrationDate: '12 DEC 2025',
    assetHoldings: 110000,
    affiliates: 10,
    status: 'Blocked',
    kycStatus: 'Need Information',
    lastLogin: '05 DEC 2025',
    avatarUrl: '/images/profile-image.png',
    country: 'Spain',
    phone: '91234567901',
    ip: '128.1.123.111',
    referral: 'referral.linda@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 10,
  },
  {
    id: '12180013',
    username: 'mikeMosaic',
    name: 'Michael Young',
    email: 'michael.young@gmail.com',
    registrationDate: '12 JAN 2026',
    assetHoldings: 150000,
    affiliates: 18,
    status: 'Active',
    kycStatus: 'Approved',
    lastLogin: '10 JAN 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'France',
    phone: '91234567902',
    ip: '128.1.123.112',
    referral: 'referral.michael@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 18,
  },
  {
    id: '12180014',
    username: 'novemberNerd',
    name: 'Nina Kelly',
    email: 'nina.kelly@gmail.com',
    registrationDate: '05 FEB 2026',
    assetHoldings: 120400,
    affiliates: 4,
    status: 'Suspended',
    kycStatus: 'Need Information',
    lastLogin: '15 FEB 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'Germany',
    phone: '91234567903',
    ip: '128.1.123.113',
    referral: 'referral.nina@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 4,
  },
  {
    id: '12180015',
    username: 'oscarOrbit',
    name: 'Oliver Price',
    email: 'oliver.price@gmail.com',
    registrationDate: '20 MAR 2026',
    assetHoldings: 98000,
    affiliates: 19,
    status: 'Inactive',
    kycStatus: 'Approved',
    lastLogin: '20 MAR 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'Spain',
    phone: '91234567904',
    ip: '128.1.123.114',
    referral: 'referral.oliver@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 19,
  },
  {
    id: '12180016',
    username: 'papaPixel',
    name: 'Paula Reed',
    email: 'paula.reed@gmail.com',
    registrationDate: '15 APR 2026',
    assetHoldings: 132000,
    affiliates: 16,
    status: 'Blocked',
    kycStatus: 'Need Information',
    lastLogin: '25 APR 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'France',
    phone: '91234567905',
    ip: '128.1.123.115',
    referral: 'referral.paula@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 16,
  },
  {
    id: '12180017',
    username: 'quebecQuest',
    name: 'Quinn Rogers',
    email: 'quinn.rogers@gmail.com',
    registrationDate: '08 MAY 2026',
    assetHoldings: 123500,
    affiliates: 3,
    status: 'Active',
    kycStatus: 'Approved',
    lastLogin: '30 MAY 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'Germany',
    phone: '91234567906',
    ip: '128.1.123.116',
    referral: 'referral.quinn@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 3,
  },
  {
    id: '12180018',
    username: 'romeoRhythm',
    name: 'Rachel Bell',
    email: 'rachel.bell@gmail.com',
    registrationDate: '22 JUN 2026',
    assetHoldings: 115000,
    affiliates: 21,
    status: 'Suspended',
    kycStatus: 'Need Information',
    lastLogin: '05 JUN 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'Spain',
    phone: '91234567907',
    ip: '128.1.123.117',
    referral: 'referral.rachel@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 21,
  },
  {
    id: '12180019',
    username: 'sierraSync',
    name: 'Stephen Hill',
    email: 'stephen.hill@gmail.com',
    registrationDate: '12 JUL 2026',
    assetHoldings: 140000,
    affiliates: 9,
    status: 'Inactive',
    kycStatus: 'Approved',
    lastLogin: '10 JUL 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'France',
    phone: '91234567908',
    ip: '128.1.123.118',
    referral: 'referral.stephen@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 9,
  },
  {
    id: '12180020',
    username: 'tangoTrail',
    name: 'Tina Brooks',
    email: 'tina.brooks@gmail.com',
    registrationDate: '05 AUG 2026',
    assetHoldings: 127000,
    affiliates: 17,
    status: 'Blocked',
    kycStatus: 'Need Information',
    lastLogin: '15 AUG 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'Germany',
    phone: '91234567909',
    ip: '128.1.123.119',
    referral: 'referral.tina@example.com',
    AffiliateStatus: 'Yes',
    is_demo: false,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 17,
  },
  {
    id: '12180021',
    username: 'uniformUx',
    name: 'Ulysses Clark',
    email: 'ulysses.clark@gmail.com',
    registrationDate: '20 SEP 2026',
    assetHoldings: 163000,
    affiliates: 14,
    status: 'Active',
    kycStatus: 'Approved',
    lastLogin: '20 SEP 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'Spain',
    phone: '91234567910',
    ip: '128.1.123.120',
    referral: 'referral.ulysses@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 14,
  },
  {
    id: '12180022',
    username: 'victorVoice',
    name: 'Victoria Diaz',
    email: 'victoria.diaz@gmail.com',
    registrationDate: '15 OCT 2026',
    assetHoldings: 138000,
    affiliates: 6,
    status: 'Suspended',
    kycStatus: 'Need Information',
    lastLogin: '25 OCT 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'France',
    phone: '91234567911',
    ip: '128.1.123.121',
    referral: 'referral.victoria@example.com',
    AffiliateStatus: 'No',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 6,
  },
  {
    id: '12180023',
    username: 'whiskeyWave',
    name: 'Walter Scott',
    email: 'walter.scott@gmail.com',
    registrationDate: '08 NOV 2026',
    assetHoldings: 129000,
    affiliates: 12,
    status: 'Inactive',
    kycStatus: 'Approved',
    lastLogin: '30 NOV 2026',
    avatarUrl: '/images/profile-image.png',
    country: 'Germany',
    phone: '91234567912',
    ip: '128.1.123.122',
    referral: 'referral.walter@example.com',
    AffiliateStatus: 'Yes',
    is_demo: true,
    is_admin: false,
    is_rewards_enabled: true,
    meta_assets_count: 12,
    noOfAffiliates: 12,
  },
];
